"use strict";
// let notSure: any = 4;
// notSure = '문자일수도 있어';
// notSure = false;
var notSure = 4;
notSure.ifItExists();
notSure.toFixed();
// let notSure: Object = 4;
// notSure.toFixed();
// let list: any = [1, true, 'free'];
// list[1] = 100;
